= Library

== add-cursor-character-unicode-expansion

Show Unicode value in the status line.

Run `add-cursor-character-unicode-expansion` and add `%opt{cursor_character_unicode}` expansion to your status line.

--------------------------------------------------------------------------------
add-cursor-character-unicode-expansion
set-option global modelinefmt '%opt{cursor_character_unicode}'
--------------------------------------------------------------------------------

add `%opt{cursor_character_unicode}` expansion.

== delete-scratch-message

--------------------------------------------------------------------------------
delete-scratch-message
--------------------------------------------------------------------------------

== find, f

--------------------------------------------------------------------------------
map -docstring 'open file' global normal <c-f> ':find<space>'
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
set-option global find_command 'fd --type file'
--------------------------------------------------------------------------------

== open-kakrc

== source-kakrc

== source-runtime

--------------------------------------------------------------------------------
source-runtime rc/filetype/crystal.kak
--------------------------------------------------------------------------------

source from `%val{runtime}`.

== source-config

--------------------------------------------------------------------------------
source-config colors/dracula.kak
--------------------------------------------------------------------------------

source from `%val{config}`.

== evaluate-selections, =

== evaluate-commands-pure

--------------------------------------------------------------------------------
evaluate-commands -pure [switches] <commands>
--------------------------------------------------------------------------------

== append-text

--------------------------------------------------------------------------------
append-text 'Hello, World!'
--------------------------------------------------------------------------------

== insert-text

--------------------------------------------------------------------------------
insert-text 'Hello, World!'
--------------------------------------------------------------------------------

== replace-text

--------------------------------------------------------------------------------
replace-text 'Hello, World!'
--------------------------------------------------------------------------------

== indent-selections

replace leading tabs with the appropriate indent and align everything with the current line.

== sort-selections

== reverse-selections

== math

--------------------------------------------------------------------------------
map -docstring 'math' global normal = ':math<ret>'
--------------------------------------------------------------------------------

== show-selected-text

--------------------------------------------------------------------------------
show-selected-text
--------------------------------------------------------------------------------

Blue (alpha-blended) face:

--------------------------------------------------------------------------------
set-face global SelectedText "default,rgba:%opt{blue}%opt{selection_alpha}"
--------------------------------------------------------------------------------

== hide-selected-text

== show-palette

--------------------------------------------------------------------------------
map -docstring 'show palette' global view p '<esc>:show-palette<ret>'
--------------------------------------------------------------------------------

== make-directory-on-save

--------------------------------------------------------------------------------
make-directory-on-save
--------------------------------------------------------------------------------

== synchronize-clipboard

--------------------------------------------------------------------------------
synchronize-clipboard
--------------------------------------------------------------------------------

== synchronize-buffer-directory-name-with-register

--------------------------------------------------------------------------------
synchronize-buffer-directory-name-with-register d
--------------------------------------------------------------------------------
